### PR TITLE
Update charts for Cilium v1.14.12

### PR DESCRIPTION
**Pull request by qmonnet**
Based on top of https://github.com/cilium/charts/pull/130
Related to: https://github.com/cilium/release/issues/210

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Review by joestringer — CHANGES_REQUESTED** [review]
Oh, actually this is adding two right?

**Comment by qmonnet** [comment]
I intend to merge it after the other PR for 1.15.6, at which point I expect the first commit to be already in `master`

**Comment by qmonnet** [comment]
The motivation is to do the create PR in parallel, hopefully without creating merge conflicts.

**Comment by qmonnet** [comment]
... which didn't work :disappointed: 

I'll rebase this one now.

**Comment by joestringer** [comment]
I see yeah. I *think* that if you push the branch into this repository, and target one PR to merge into the next PR, then after merging, github may automatically rebase this one after merging the first. Might be a strategy for future.

**Comment by joestringer** [comment]
Or we can just automate this step through dispatch requests in github workflows. :soon:

**Review by joestringer — APPROVED** [review]

**Pull request merged**
